name: test
on:
   workflow_dispatch:
jobs:
   do-the-job:
    name: system_tests_win32
    runs-on: test
    timeout-minutes: 40
    strategy:
      matrix:
        module_name:
          [
            "nidigital",
            "nitclk",
            "nifgen",
            "nidcpower",
            "nidmm",
            "niscope",
            "nimodinst",
            "nise",
            "niswitch",
          ]
    steps:
      - name: system_tests_win32
        uses: SukruthGrandhiNI/githubactions@master
        with:
          module_name: ${{ matrix.module_name }}
