name: nimibot_win_32_local

on: 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
   pull_request:
     branches:
       - master
       - releases/*

jobs:
  do-the-job1:
    name: system_tests_long
    runs-on: 
    - self-hosted
    - windows
    - x64
    - test-rdss-nimibot-win-10-py32
    timeout-minutes: 60
    strategy:
      matrix:
        module_name:
          [
            "nidigital",
            "nitclk",
          ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2    
      - name: run system tests
        run: |
          cd generated        
          mkdir junit
          mkdir kibana
          cd ${{ matrix.module_name }}
          python -m tox -c tox-system_tests.ini        
        shell: powershell
        
  do-the-job2:
    name: system_tests_fast
    runs-on: 
    - self-hosted
    - windows
    - x64
    - test-rdss-nimibot-win-10-py32
    timeout-minutes: 40
    strategy:
      matrix:
        module_name:
          [
            "nifgen",
            "nidcpower",
            "nidmm",
            "niscope",
            "nimodinst",
            "nise",
            "niswitch",
          ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2    
      - name: run system tests
        run: |
          cd generated        
          mkdir junit
          mkdir kibana
          cd ${{ matrix.module_name }}
          python -m tox -c tox-system_tests.ini        
        shell: powershell
