name: nimibot_win_32_local

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  do-the-job:
    name: system_tests
    runs-on: example
    steps:
      - name: checkout repository
        uses: actions/checkout@v2    
