name: nimibot_win_32

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-ids: ${{ steps.start-ec2-runner.outputs.ec2-instance-ids }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: ni/ec2-github-runner@users/krlydm/0119_mkdirfix
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-base-os: win-x64
          ec2-launch-template: rdss-nimibot-windows-python32
          number-of-runners: 1
          number-of-instances: 4
          ec2-instance-type: t3.medium

  do-the-job1:
    name: system_tests_1
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    timeout-minutes: 40
    strategy:
      matrix:
        module_name:
          [
            "nidmm",
            "niscope",
            "nimodinst",
            "nise",
            "niswitch",
          ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2    
      - name: run system tests
        run: |
          cd generated        
          mkdir junit
          mkdir kibana
          cd ${{ matrix.module_name }}
          python -m tox -c tox-system_tests.ini        
        shell: powershell
        
  do-the-job2:
    name: system_tests_2
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    timeout-minutes: 40
    strategy:
      matrix:
        module_name:
          [
            "nidigital",
            "nitclk",
            "nifgen",
            "nidcpower",
          ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2    
      - name: run system tests
        run: |
          cd generated        
          mkdir junit
          mkdir kibana
          cd ${{ matrix.module_name }}
          python -m tox -c tox-system_tests.ini        
        shell: powershell

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - do-the-job1 # required to wait when the main job is done
      - do-the-job2 # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: ni/ec2-github-runner@users/krlydm/0119_mkdirfix
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-ids: ${{ needs.start-runner.outputs.ec2-instance-ids }}
